[package]
name = "broken_ownership"
version = "0.1.0"
authors = ["Sander Julien-Saint-Amand <sander.julien-saint-amand@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
